In [4]:
import numpy as np 
import matplotlib.pyplot as plt

In [5]:
#À régler: la fonction commence à faire des trucs bizarres avec un pas de 0.3 par exemple.

def creer_maillage(x_min : float, x_max : float, y_min : float, y_max : float, z_min : float, z_max : float, pas_du_maillage : float) -> tuple:
    """
    La fonction créer_maillage prend en entrée 6 float qui permettent de délémiter les bords du maillage et un pas.
    Le pas du maillage représente la distance séparant un point du prochain. 
    
    Elle renvoie un tuple de 3 arrays contenant eux-même N-array qui représentent toutes les combinaisons possibles
    discrétisant ainsi notre maillage en un  ensemble de points.
    """ 
    nb_points_entre_x_min_x_max = int((x_max - x_min) / (pas_du_maillage)) + 1
    nb_points_entre_y_min_y_max = int((y_max - y_min) / (pas_du_maillage)) + 1
    nb_points_entre_z_min_z_max = int((z_max - z_min) / (pas_du_maillage)) + 1

    axe_x = np.linspace(x_min,x_max,nb_points_entre_x_min_x_max)
    axe_y = np.linspace(y_min,y_max,nb_points_entre_y_min_y_max)
    axe_z = np.linspace(z_min,z_max,nb_points_entre_z_min_z_max)

    maillage = np.meshgrid(axe_x,axe_y,axe_z)

    return maillage

cote = 2
X,Y,Z = creer_maillage(-cote,cote,-3,3,-4,4,1)

def show_array(X : np.array, Y : np.array, Z : np.array, afficher_plot : bool, afficher_array : bool) -> tuple:
    """
    La fonction show_array() prend en entrée 3 matrices X,Y,Z et deux booléens et affiche la matrice et son plot s'il existe. 
    """
    if afficher_plot:
        fig = plt.figure()
        ax = fig.add_subplot(111, projection='3d')
        ax.set_xlabel('x')
        ax.set_ylabel('y')
        ax.set_title('Représentation 3D des valeurs des matrices')
        try:
            ax.scatter(X,Y,Z)
        except:
            return print('La matrice ne peut pasa être plot comme cela.')
    if afficher_array:
        return print(f"La première matrice ressemble à :\n \n {X},\n \nLa deuxième matrice ressemble à :\n \n {Y},\n \nLa dernière matrice ressemble à :\n \n {Z}")
    return None 

show_array(X,Y,Z,False,True)

La première matrice ressemble à :
 
 [[[-2. -2. -2. -2. -2. -2. -2. -2. -2.]
  [-1. -1. -1. -1. -1. -1. -1. -1. -1.]
  [ 0.  0.  0.  0.  0.  0.  0.  0.  0.]
  [ 1.  1.  1.  1.  1.  1.  1.  1.  1.]
  [ 2.  2.  2.  2.  2.  2.  2.  2.  2.]]

 [[-2. -2. -2. -2. -2. -2. -2. -2. -2.]
  [-1. -1. -1. -1. -1. -1. -1. -1. -1.]
  [ 0.  0.  0.  0.  0.  0.  0.  0.  0.]
  [ 1.  1.  1.  1.  1.  1.  1.  1.  1.]
  [ 2.  2.  2.  2.  2.  2.  2.  2.  2.]]

 [[-2. -2. -2. -2. -2. -2. -2. -2. -2.]
  [-1. -1. -1. -1. -1. -1. -1. -1. -1.]
  [ 0.  0.  0.  0.  0.  0.  0.  0.  0.]
  [ 1.  1.  1.  1.  1.  1.  1.  1.  1.]
  [ 2.  2.  2.  2.  2.  2.  2.  2.  2.]]

 [[-2. -2. -2. -2. -2. -2. -2. -2. -2.]
  [-1. -1. -1. -1. -1. -1. -1. -1. -1.]
  [ 0.  0.  0.  0.  0.  0.  0.  0.  0.]
  [ 1.  1.  1.  1.  1.  1.  1.  1.  1.]
  [ 2.  2.  2.  2.  2.  2.  2.  2.  2.]]

 [[-2. -2. -2. -2. -2. -2. -2. -2. -2.]
  [-1. -1. -1. -1. -1. -1. -1. -1. -1.]
  [ 0.  0.  0.  0.  0.  0.  0.  0.  0.]
  [ 1.  1.  1.  1.  1.  1.  1.  1. 

In [6]:
def find_valeurs_point(x : float, y : float, z : float, X : np.array, Y : np.array, Z : np.array) -> tuple:
    """
    Cette fonction permet en prenant 3 matrices X,Y,Z de la même forme que celles issues de la fonction 
    creer_maillage() en attribut et 3 points correspondant au point de l'espace considéré dont on veut connaître les
    valeurs associées à X,Y,Z.
    """
    nb_points_x = np.shape(X[0])[0]
    nb_points_y = len(X)
    nb_points_z = np.shape(X[0])[1]

    val_min_x = X[0][0,0]
    val_max_x = X[0][nb_points_x-1,0]
    val_min_y = Y[0][0,0]
    val_max_y = Y[nb_points_y-1][0,0]
    val_min_z = Z[0][0,0]
    val_max_z = Z[0][0,nb_points_z-1]

    if (nb_points_x-1) != 0 and (nb_points_y-1) != 0 and (nb_points_z-1) != 0:
        pas_suivant_x = int((int(val_max_x - val_min_x))  / (nb_points_x - 1))
        pas_suivant_y = int((int(val_max_y - val_min_y))  / (nb_points_y - 1))
        pas_suivant_z = int((int(val_max_z - val_min_z))  / (nb_points_z - 1))
    else:
        raise ZeroDivisionError()
    
    val_indice_x = 

SyntaxError: invalid syntax (4078576956.py, line 25)